"""updated Question table

Revision ID: d5f6a9197c35
Revises: d66def8b9a1c
Create Date: 2020-04-25 13:14:05.860943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f6a9197c35'
down_revision = 'd66def8b9a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('question', sa.Column('question', sa.String(length=255), nullable=False))
    op.drop_column('question', 'ques_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('ques_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.drop_column('question', 'question')
    op.drop_column('question', 'options')
    # ### end Alembic commands ###
